re-order the gdal probe, and brew uninstall gdal beforehand

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -125,14 +125,6 @@ jobs:
           which perl
           otool -L `perl -MAlien::GDAL -E'print Alien::gdal->dist_dir'`/lib/libgdal.dylib
           
-      - name: GDAL probe
-        run: |
-          perl etc/probe_gdal.pl
-          pp_autolink -o probe_gdal etc/probe_gdal.pl
-          ./probe_gdal || {
-            echo "Binary failed to run!" >&2
-            exit 0  #  don't cripple the caching by failing
-          }
 
       - name: Clone biodiverse repo
         run: | 
@@ -174,7 +166,7 @@ jobs:
 
       - name: Uninstall brew deps
         run: |
-          brew uninstall gdk-pixbuf gtk+3
+          brew uninstall gdk-pixbuf gtk+3 gdal
 
 
       - name: Try to run the packed archive
@@ -184,3 +176,12 @@ jobs:
             exit 0  #  don't cripple the caching by failing
           }
           
+          
+      - name: GDAL probe
+        run: |
+          perl etc/probe_gdal.pl
+          pp_autolink -o probe_gdal etc/probe_gdal.pl
+          ./probe_gdal || {
+            echo "Binary failed to run!" >&2
+            exit 0  #  don't cripple the caching by failing
+          }
