reorder

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -150,6 +150,17 @@ jobs:
         with:
           name: cpanm_dir
           path: ~/.cpanm
+          
+          
+      - name: GDAL probe 1
+        run: |
+          perl etc/probe_gdal.pl
+          pp_autolink -o probe_gdal etc/probe_gdal.pl
+          ./probe_gdal || {
+            echo "Binary failed to run!" >&2
+            exit 0  #  don't cripple the caching by failing
+          }
+
 
       #- name: Check Biodiverse can run, except that it hangs
       #  run: prove -l biodiverse/t
@@ -179,15 +190,6 @@ jobs:
           name: dmg-file
           #path: ${DMG_FILE_NAME}
           path: ./builds/Biodiverse-*.dmg
-
-      - name: GDAL probe 1
-        run: |
-          perl etc/probe_gdal.pl
-          pp_autolink -o probe_gdal etc/probe_gdal.pl
-          ./probe_gdal || {
-            echo "Binary failed to run!" >&2
-            exit 0  #  don't cripple the caching by failing
-          }
 
       - name: Uninstall brew deps
         run: |
