CI: brew uninstall some deps and check we can run

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -92,6 +92,7 @@ jobs:
           #cpanm --notest Task::Biodiverse::NoGUI
           cpanm --notest ExtUtils::PkgConfig
           cpanm --notest ExtUtils::Depends
+          cpanm --notest Glib::Object::Introspection
           cpanm --notest Gtk3
           cpanm --notest PAR::Packer
           cpanm --notest File::BaseDir
@@ -140,3 +141,15 @@ jobs:
           name: dmg-file
           #path: ${DMG_FILE_NAME}
           path: ./builds/Biodiverse-*.dmg
+
+      - name: Uninstall brew deps
+        run: |
+          brew uninstall gdk-pixbuf gtk+3
+      
+      - name: Try to run the packed archive
+        run: |
+          ./builds/Biodiverse.app/Contents/MacOS/BiodiverseGUI || {
+            echo "Binary failed to run!" >&2
+            exit 0  #  don't cripple the caching by failing
+          }
+          
