Add and use a gdal probe script

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -118,6 +118,14 @@ jobs:
         run: |
           which perl
           otool -L `perl -MAlien::GDAL -E'print Alien::gdal->dist_dir'`/lib/libgdal.dylib
+      - name: GDAL probe
+        run: |
+          perl etc/probe_gdal.pl
+          pp_autolink -o probe_gdal etc/probe_gdal
+          ./probe_gdal || {
+            echo "Binary failed to run!" >&2
+            exit 0  #  don't cripple the caching by failing
+          }
 
       - name: Clone biodiverse repo
         run: | 
