Back to full build

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -60,6 +60,9 @@ jobs:
           path
           perl -V
 
+        #  These dirs must exist before caching 
+        #  is first called or it will not work.
+        #  The upload action also does not like dirs with leading dots.
       - name: Make the cache dir
         shell: pwsh
         run: |
@@ -93,63 +96,63 @@ jobs:
           cpanm --notest --reinstall --verbose Browser::Start
           ls \Users\runner\perl5
 
-      # - name: Install cpan deps 
-        # shell: pwsh
-        # run: |
-          # $env:CMAKE_BUILD_PARALLEL_LEVEL=4
-          # # set PATH=%SP_PATHS%;%PATH%
-          # # path
-          # $env:PATH = "$env:SP_PATHS;$env:PATH"
-          # echo $env:PATH
-          # # set PERL_CPANM_HOME=/Users/runner/.cpanm
-          # perl -E'say $^V'
-          # cpanm --notest PAR::Packer
-          # cpanm App::PP::Autolink
-          # where pp_autolink.pl
-          # cpanm --notest Alien::MSYS
-          # cpanm --notest Alien::libtiff
-          # cpanm --notest Alien::sqlite
-          # cpanm --notest --installdeps Alien::geos::af
-          # cpanm --notest -v Alien::geos::af
-          # cpanm --notest --installdeps Alien::proj
-          # cpanm --notest -v Alien::proj
-          # cpanm --notest --installdeps Alien::gdal
-          # $env:ALIEN_GDAL_CMAKE_ARGS = "-DGDAL_ENABLE_DRIVER_PDF:BOOL=OFF -DGDAL_USE_CURL=OFF -DBUILD_APPS=OFF"
-          # $env:ALIEN_INSTALL_TYPE = "share"
-          # cpanm --notest -v Alien::gdal
-          # cpanm https://github.com/shawnlaffan/biodiverse-utils/releases/download/v1.09/Biodiverse-Utils-1.09.tar.gz
-          # cpanm https://github.com/shawnlaffan/perl-alien-gtkstack-windows.git
-          # ppm set repository biodiverse https://github.com/shawnlaffan/perl-alien-gtkstack-windows/releases/download/first_upload/
-          # ppm install Cairo
-          # ppm install Cairo-GObject
-          # ppm install Glib
-          # ppm install Gnome2-Canvas
-          # ppm install Gtk2
-          # ppm install Pango
-          # cpanm --notest File::BaseDir
-          # cpanm --notest File::Find::Rule
-          # cpanm --notest Browser::Start
-          # cpanm --notest ExtUtils::Depends
-          # cpanm --notest HTTP::Tiny
-          # cpanm --notest IO::Socket::SSL
-          # cpanm --notest LWP::Simple
-          # cpanm --notest Geo::ShapeFile
-          # cpanm --notest autovivification
-          # cpanm --installdeps --notest Geo::GDAL::FFI
-          # cpanm Geo::GDAL::FFI
+      - name: Install cpan deps 
+        shell: pwsh
+        run: |
+          $env:CMAKE_BUILD_PARALLEL_LEVEL=4
+          # set PATH=%SP_PATHS%;%PATH%
+          # path
+          $env:PATH = "$env:SP_PATHS;$env:PATH"
+          echo $env:PATH
+          # set PERL_CPANM_HOME=/Users/runner/.cpanm
+          perl -E'say $^V'
+          cpanm --notest PAR::Packer
+          cpanm App::PP::Autolink
+          where pp_autolink.pl
+          cpanm --notest Alien::MSYS
+          cpanm --notest Alien::libtiff
+          cpanm --notest Alien::sqlite
+          cpanm --notest --installdeps Alien::geos::af
+          cpanm --notest -v Alien::geos::af
+          cpanm --notest --installdeps Alien::proj
+          cpanm --notest -v Alien::proj
+          cpanm --notest --installdeps Alien::gdal
+          $env:ALIEN_GDAL_CMAKE_ARGS = "-DGDAL_ENABLE_DRIVER_PDF:BOOL=OFF -DGDAL_USE_CURL=OFF -DBUILD_APPS=OFF"
+          $env:ALIEN_INSTALL_TYPE = "share"
+          cpanm --notest -v Alien::gdal
+          cpanm https://github.com/shawnlaffan/biodiverse-utils/releases/download/v1.09/Biodiverse-Utils-1.09.tar.gz
+          cpanm https://github.com/shawnlaffan/perl-alien-gtkstack-windows.git
+          ppm set repository biodiverse https://github.com/shawnlaffan/perl-alien-gtkstack-windows/releases/download/first_upload/
+          ppm install Cairo
+          ppm install Cairo-GObject
+          ppm install Glib
+          ppm install Gnome2-Canvas
+          ppm install Gtk2
+          ppm install Pango
+          cpanm --notest File::BaseDir
+          cpanm --notest File::Find::Rule
+          cpanm --notest Browser::Start
+          cpanm --notest ExtUtils::Depends
+          cpanm --notest HTTP::Tiny
+          cpanm --notest IO::Socket::SSL
+          cpanm --notest LWP::Simple
+          cpanm --notest Geo::ShapeFile
+          cpanm --notest autovivification
+          cpanm --installdeps --notest Geo::GDAL::FFI
+          cpanm Geo::GDAL::FFI
 
-      # - name: Clone biodiverse repo
-        # shell: pwsh
-        # run: |
-          # # set PATH=%SP_PATHS%;%PATH%
-          # $env:PATH = "$env:SP_PATHS;$env:PATH"
-          # perl -E'say $^V'
-          # git clone --depth=1 https://github.com/shawnlaffan/biodiverse.git
-          # cd biodiverse
-          # cpanm --installdeps .
-          # # prove t/00-load.t || true  #  allow caching even if we fail
-          # # prove -j4 -l t
-          # cd ..
+      - name: Clone biodiverse repo
+        shell: pwsh
+        run: |
+          # set PATH=%SP_PATHS%;%PATH%
+          $env:PATH = "$env:SP_PATHS;$env:PATH"
+          perl -E'say $^V'
+          git clone --depth=1 https://github.com/shawnlaffan/biodiverse.git
+          cd biodiverse
+          cpanm --installdeps .
+          # prove t/00-load.t || true  #  allow caching even if we fail
+          # prove -j4 -l t
+          cd ..
           
       #  uncomment when the rest of the process works
       # - name: PAR::Packer with Biodiverse icon
